# Generated by Django 4.2.5 on 2023-11-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientprofile_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
