# Generated by Django 4.2.5 on 2023-11-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clientprofile_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
