# Generated by Django 4.2.5 on 2023-11-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clientprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.BooleanField(default=False),
        ),
    ]
