# Generated by Django 4.2.5 on 2023-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
