# Generated by Django 4.2.5 on 2023-11-27 00:47

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.CharField(max_length=11, null=True, validators=[apps.common.validators.validate_bvn]),
        ),
    ]
