# Generated by Django 4.2.5 on 2023-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Full name'),
        ),
    ]
