# Generated by Django 4.2.5 on 2023-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_business_owner_invoice_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_on',
            field=models.DateTimeField(null=True),
        ),
    ]
