# Generated by Django 4.2.5 on 2023-11-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_account_number_wallet_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='flw_ref',
            new_name='order_ref',
        ),
    ]
